### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'sendToQueue')

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/discord-bot#56]
```
TypeError: Cannot read properties of undefined (reading 'sendToQueue')
development-tc-server-comm-dev-1  | 2023-06-02T15:29:44.877817582Z     at RabbitMQ.publish (/user/app/node_modules/@togethercrew.dev/tc-messagebroker/dist/rabbitmq/rabbit.js:54:22)
development-tc-server-comm-dev-1  | 2023-06-02T15:29:44.877824013Z     at model.start (/user/app/node_modules/@togethercrew.dev/tc-messagebroker/dist/models/schemas/methods/saga.schema.methods.js:16:24)
development-tc-server-comm-dev-1  | 2023-06-02T15:29:44.877829450Z     at Object.<anonymous> (/user/app/lib/services/saga.service.js:20:20)
development-tc-server-comm-dev-1  | 2023-06-02T15:29:44.877834590Z     at Generator.next (<anonymous>)
development-tc-server-comm-dev-1  | 2023-06-02T15:29:44.877839014Z     at fulfilled (/user/app/lib/services/saga.service.js:5:58)
development-tc-server-comm-dev-1  | 2023-06-02T15:29:44.877843572Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by scientiststwin** [comment]
publish method/Saga start should be called after RabbitMQ is connected.
